name: ChatFeelingsTerry
main: com.terryviento.chatfeelings.Main
website: https://github.com/TerryViento/ChatFeelings
authors: [TerryViento]
version: 4.16-B01
api-version: 1.13
softdepend: [Essentials, VanishNoPacket, LiteBans, AdvancedBan, PlaceholderAPI]
description: Permite que tus jugadores expresen su amor u odio con emotes únicos.
folia-supported: true
commands:
  chatfeelings:
    description: Comando general para ChatFeelings.
  sentimientos:
    description: Muestra todos los sentimientos disponibles.
    aliases: [ emociones, feelings ]
  abrazo:
    description: Dale a alguien un abrazo bien cálido.
  bofetada:
    description: Devuelve a alguien a la realidad con una bofetada.
  picar:
    description: Pica a alguien para llamar su atención.
  chocala:
    description: Demuestra tu apoyo chocando los cinco.
  palmada:
    description: Expresa desaprobación con una palmada en la cara.
  gritar:
    description: Grita a alguien tan fuerte como puedas.
  morder:
    description: Muerde a un jugador directo en el brazo.
  acurrucar:
    description: Acurrúcate con el poder de los abrazos cálidos.
  sacudir:
    description: Sacude a un jugador hasta ponerlo en pie.
  acuchillar:
    description: Apuñala a alguien con un cuchillo. ¡Ay!
  besar:
    description: Da un dulce beso lleno de cariño.
  golpear:
    description: Golpea a alguien con todas tus fuerzas.
  asesinar:
    description: Lleva la rivalidad al extremo mortal.
  llorar:
    description: ¿Horas tristes? Llora con alguien.
  oye:
    description: Lánzale un sonoro «oye» a un jugador.
  dabear:
    description: Presume haciendo un dab frente a alguien.
  lamer:
    description: Lame a alguien como si fuera un helado.
  despreciar:
    description: Avergüenza a un jugador por lo que hizo.
  acariciar:
    description: Acaricia la cabeza de un jugador por ser bueno.
  acechar:
    description: Acecha a un jugador con sigilo.
  sospechar:
    description: Míralo con una sospecha de un solo hueso.
  saludar:
    description: Despídete con elegancia agitando la mano.
  bienvenido:
    description: Da la bienvenida de regreso a los jugadores.
  tocar:
    description: Tócale suavemente la nariz a alguien.
  tetazo:
    description: Lanza un épico tetazo amistoso.
  punalada:
    description: Asesta una puñalada certera.
permissions:
  chatfeelings.*:
    description: Permite todos los sentimientos, comandos y acciones administrativas de ChatFeelings.
    children:
      chatfeelings.admin: true
      chatfeelings.stats: true
      chatfeelings.stats.others: true
      chatfeelings.mute: true
      chatfeelings.ignore: true
      chatfeelings.bypasscooldowns: true
      chatfeelings.all: true
  chatfeelings.all:
    description: Permite acceder a todos los sentimientos de ChatFeelings.
    default: true
    children:
      chatfeelings.abrazo: true
      chatfeelings.bofetada: true
      chatfeelings.picar: true
      chatfeelings.chocala: true
      chatfeelings.palmada: true
      chatfeelings.gritar: true
      chatfeelings.morder: true
      chatfeelings.acurrucar: true
      chatfeelings.sacudir: true
      chatfeelings.besar: true
      chatfeelings.golpear: true
      chatfeelings.asesinar: true
      chatfeelings.llorar: true
      chatfeelings.oye: true
      chatfeelings.dabear: true
      chatfeelings.lamer: true
      chatfeelings.acariciar: true
      chatfeelings.acechar: true
      chatfeelings.sospechar: true
      chatfeelings.saludar: true
      chatfeelings.bienvenido: true
      chatfeelings.tocar: true
      chatfeelings.tetazo: true
      chatfeelings.punalada: true
      chatfeelings.acuchillar: true
      chatfeelings.despreciar: true
  chatfeelings.abrazo:
    default: true
  chatfeelings.bofetada:
    default: true
  chatfeelings.picar:
    default: true
  chatfeelings.chocala:
    default: true
  chatfeelings.palmada:
    default: true
  chatfeelings.gritar:
    default: true
  chatfeelings.morder:
    default: true
  chatfeelings.acurrucar:
    default: true
  chatfeelings.sacudir:
    default: true
  chatfeelings.acuchillar:
    default: true
  chatfeelings.besar:
    default: true
  chatfeelings.golpear:
    default: true
  chatfeelings.asesinar:
    default: true
  chatfeelings.llorar:
    default: true
  chatfeelings.oye:
    default: true
  chatfeelings.dabear:
    default: true
  chatfeelings.lamer:
    default: true
  chatfeelings.despreciar:
    default: true
  chatfeelings.acariciar:
    default: true
  chatfeelings.acechar:
    default: true
  chatfeelings.sospechar:
    default: true
  chatfeelings.saludar:
    default: true
  chatfeelings.bienvenido:
    default: true
  chatfeelings.tocar:
    default: true
  chatfeelings.tetazo:
    default: true
  chatfeelings.punalada:
    default: true
  chatfeelings.admin:
    default: op
  chatfeelings.stats:
    default: true
  chatfeelings.stats.others:
    default: op
  chatfeelings.mute:
    default: op
  chatfeelings.ignore:
    default: op
  chatfeelings.bypasscooldowns:
    default: op